### ISSUE TITLE
Copy button for sharing

### ISSUE THREAD

**Issue by jonsatrom** [netizenorg/netnet.studio#107]
A button to copy the URL for sharing could be helpful for novices.

**Comment by nbriz** [comment]
i've got the URL highlighted by default (so u can quickly cmd/cntrl+C) adding to data to the system clipboard via JS has always been tricky. back in the day folks did that w/Flash. there was an API for it at one point, but it got [depreciated](https://developer.mozilla.org/en-US/docs/Web/API/document/execCommand), there's a [new one](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/write), but i've never gotten it to work (maybe b/c it's [still a draft](https://w3c.github.io/clipboard-apis/#clipboard-events-and-interfaces)?)

i just looked into GitHub's code to see how they do their copy button for git clone URLs && seems they made a [custom element ](https://github.com/github/clipboard-copy-element)for it (which we might just be able to plugin if it works).
