### ISSUE TITLE
hiding shorties

### ISSUE THREAD

**Issue by jonsatrom** [netizenorg/netnet.studio#109]
minor edge case/path
User Path --->
Read the dialogue and select "hide from view?"
**Read the dialogue and select "yes please, I prefer you hide"**
Read the dialogue and select "why is the URL so long?"
Read the dialogue and select "let's shorten it!"
Read the dialogue and select "fine with me!"
netnet forgets that I hid code before shortening

**Comment by nbriz** [comment]
dang, nice find. 
in the deep depths of conditional logic
🤿

**Comment by nbriz** [comment]
fixed in this PR: https://github.com/netizenorg/netnet.studio/pull/159
