### ISSUE TITLE
Refactor older styles

### ISSUE THREAD

**Issue by sarahrooney** [netizenorg/netnet.studio#151]
Establish a standardized CSS methodology across all style files, new and old.
Changes include:
[BEM](http://getbem.com/)
[Ordered declarations](https://9elements.com/css-rule-order/)

**Comment by nbriz** [comment]
rad! take notes so we can turn these standards/conventions into docs for future contributors :)

**Comment by sarahrooney** [comment]
will do! :~)

**Comment by nbriz** [comment]
@sarahrooney is this complete? if so maybe we can make a little note about the conventions in the docs somewhere && then close this issue?

**Comment by sarahrooney** [comment]
@nbriz lemme take a couple days to check over where i left off, i have a feeling i had some unfinished thoughts. i'll try to get this ticket closed (& update docs) by early next week & if i find more to do i'll make specific issues to get em done cleaner

**Comment by sarahrooney** [comment]
@nbriz with https://github.com/netizenorg/netnet.studio/pull/249 open, i think this issue can be closed, & anything else style-related can be dealt with individually rather than in one big issue! do you mind peer reviewing the PR b4 its merged? (simple changes, plus a note about the corresponding docs i'm still working on)

**Comment by sarahrooney** [comment]
PR #249 is merged, & this can be closed! style documentation [here](https://github.com/netizenorg/netnet.studio/wiki/working-on-core-functionality)
