### ISSUE TITLE
Style "Special" Widgets

### ISSUE THREAD

**Issue by sarahrooney** [netizenorg/netnet.studio#17]
widget, tutorials, and functions windows

**Comment by nbriz** [comment]
@sarahrooney hey, noticed ur working on this one now. just FYI i've got uncommitted changes to the actual Widget files (MenuFunctions.js + MenuWidgets.js) ...hopefully u don't need to edit those, but if so we should touch base (to avoide conflicts). i haven't touched the style sheets though (nor do i plan to)
