### ISSUE TITLE
DemoExampleMaker: re-order steps functionality

### ISSUE THREAD

**Issue by nbriz** [netizenorg/netnet.studio#236]
@Cthomp7 moving this out into it's own task ([from here](https://github.com/netizenorg/netnet.studio/issues/212)) as it's likely gonna take a bit longer && wanted to close that other issue since u've done so much work on that already && i want to get that published!

**Comment by Cthomp7** [comment]
@nbriz Is there any remaining tasks for this issue?

**Comment by nbriz** [comment]
@Cthomp7 not unless u can think of any :) feel free to close this issue if not

**Comment by Cthomp7** [comment]
@nbriz Sounds great! FYI It doesn't look like I have contributor access to close the issue, so you might have to do that.

**Comment by nbriz** [comment]
oops! will do :)
