### ISSUE TITLE
widget close button finicky

### ISSUE THREAD

**Issue by sarahrooney** [netizenorg/netnet.studio#243]
not sure if this is just a me-issue; documenting it just in case, so i dont forget. will update here after more investigation.

when an expand button is present, closing a widget seems to not work. expanding does work, however. could be an issue with how icons are nested inside of `.widget__top__close`. see Code Examples widget

**Comment by nbriz** [comment]
oh dang! good catch! i've gotten so used to clicking the 'Esc' key to close widgets i don't think i ever noticed this! fixing it now!

**Comment by nbriz** [comment]
@sarahrooney ok, fixed! pull changes from main :)
