### ISSUE TITLE
BG Color Tut: CSS Percentages display bug

### ISSUE THREAD

**Issue by jonsatrom** [netizenorg/netnet.studio#26]
<img width="1486" alt="Screen Shot 2020-09-14 at 12 01 57 PM" src="https://user-images.githubusercontent.com/2707761/93116047-60e4a500-f682-11ea-8dd7-1b92decc1648.png">

**Comment by nbriz** [comment]
@jonsatrom sarah fixed this in her most recent push (but i still gotta update on the server)
