### ISSUE TITLE
Interface Observations (minor)

### ISSUE THREAD

**Issue by jonsatrom** [netizenorg/netnet.studio#28]
<img width="1486" alt="Screen Shot 2020-09-14 at 12 11 26 PM" src="https://user-images.githubusercontent.com/2707761/93118331-c25a4300-f685-11ea-8ac9-8a648832155e.png">

On video:  no way to rewind (or restart vid). no way to know where you are and how long it is... (I like the lack of playhead, but some ref to where you are or how long is helpful. i.e. you may not realize it's looping.)

**Comment by nbriz** [comment]
@jonsatrom 
yea, the "hyper video player" is still the most in-progress part of this, one of the challenges w/the progress bar is that b/c of the "hypermedia" features (specifically that certain actions fire at certain points in certain videos) introducing a scrubble progress bar can cause issues. but @sarahrooney && i chatted about this yesterday && settled on adding a non-interactive progress bar, so folks know where they are / how long the vids are, but so we also avoid bugging things out (we're working on this now)

**Comment by jonsatrom** [comment]
progress bar could also simply be a counter... (fwiw)
