### ISSUE TITLE
Sections load on top of eachother

### ISSUE THREAD

**Issue by jonsatrom** [netizenorg/netnet.studio#29]
Should they "reset"?
Also  videos start where the were  left off... Should they restart at start? see #28
<img width="1486" alt="Screen Shot 2020-09-14 at 12 25 03 PM" src="https://user-images.githubusercontent.com/2707761/93118207-8c1cc380-f685-11ea-9592-dae05eab2986.png">

**Comment by nbriz** [comment]
@jonsatrom oh shit, good catch! hadn't noticed this... gotta think through this one

**Comment by nbriz** [comment]
turns out this is something i'm gonna have to fix on a per-tutorial basis:
- [ ] orientatin
- [ ] cyberspace intro
- [ ] webvr/aframe basics
