### ISSUE TITLE
Dialogue bubble not with netnet's face.

### ISSUE THREAD

**Issue by mconst2005** [netizenorg/netnet.studio#31]
@nbriz : This is minor, but after maximizing the window.

Also, netnet's dialogue is drowned by all of the widgets. I know that is the point, but you can't read what it is saying.

![20200922 - Dialogue Bubble](https://user-images.githubusercontent.com/68087939/93891471-0f0ad300-fcb1-11ea-9de2-0183d9ec2dcc.png)

**Comment by nbriz** [comment]
@mconst2005 at that point in the tutorial netnet is supposed to be in "welcome" mode (which is the layout where u don't see the code in the editor) ...did u manually switch to the dock-bottom layout? or did something else glitch out that switched the layout? (like maybe when u resized the window?)

> re: Also, netnet's dialogue is drowned by all of the widgets. I know that is the point, but you can't read what it is saying.

...yea, that's sort of the point, after they've learned that they can move windows && netnet the idea behind this section is to "test" that they've learned that. ie. they can't move to the next screen w/out demonstrating that they know how to move some of the widgets out of the way (or move netnet)
