### ISSUE TITLE
Video Tutorial/Streaming Functionality

### ISSUE THREAD

**Issue by nbriz** [netizenorg/netnet.studio#54]
...what does it mean to have video centered tutorials? for ex when we have other folks make guest tutorials? ...this still needs some concepting && then some making

**Comment by nbriz** [comment]
i've started working on video streaming functionality see https://github.com/netizenorg/netnet.studio/blob/master/www/widgets/StreamVideo.js

**Comment by jonsatrom** [comment]
❤️

**Comment by nbriz** [comment]
great WebRTC demos: https://webrtc.github.io/samples/ << putting this here so i don't loose it
