### ISSUE TITLE
starring tutorial specific widgets

### ISSUE THREAD

**Issue by nbriz** [netizenorg/netnet.studio#56]
...currently this has the unintended of effect of keeping it in the Widgets Menu even when u're not in that tutorial anymore... is this a bug? or a feature?

**Comment by nbriz** [comment]
...i'm starting to think that the "starring" functionality really isn't necessary. especially if we embrace the "self revealing interface" philosophy. @jonsatrom @sarahrooney how would u feel if i removed all the logic related to starring widgets???

**Comment by jonsatrom** [comment]
Fine by me if it’s “feeling” weird/unnecessary...
