### ISSUE TITLE
GenWidget Base Class

### ISSUE THREAD

**Issue by nbriz** [netizenorg/netnet.studio#72]
after the Widget class has got it's event system (on/emit) updated, we should probably create a new base widget class for any future widgets that function as "generators" (ie. a GUI used to generate snippets of code), similar to the ColorWidget. idea is that this widget can be extended to create specific generators like CSS gradient generator or even a new/refactored ColorWidget. the goal here would be to modularize common functionality shared between all generator widgets && as a result also create consistency in their design. 

Say we wanted to make a FontSize generator, which has a slider (similar to the ColorWidget sliders) which updates an input field containing `font-size: 24px;` such that the number updates to match the slider position, it would be ideal if we could create this widget as follows:
```js
class FontSizeWidget extends GenWidget {
  constructor (opts) {
    super(opts)
    this.data = '24px'
    this._createHTML()

    this.on('data-update', (val) => {
      this.data = val
      this.codeField.value = `font-size: ${val};`
      this.fontSlider.value = window.parseInt(val)
    })
  }

  _codeFieldUpdate (e) {
    const css = this.parceCSS(e.target.value)
    this.emit('data-update', css.value[0])
  }

  _fontSliderUpdate (e) {
    this.emit('data-update', e.target.value + 'px')
  }

  _createHTML () {
    this.codeField = this.createCodeField({
      value: 'font-size: 24px;',
      change: (e) => this._codeFieldUpdate(e)
    })

    this.fontSlider = this.createSlider({
      background: '#f00',
      min: 0,
      max: 100,
      label: 'PX',
      change: (e) => this._fontSliderUpdate(e)
    })

    const sec = document.createElement('section')
    sec.appendChild(this.fontSlider)
    sec.appendChild(this.codeField)
    this.innerHTML = sec
  }
}
```

in order for this to be possible this new GenWidget base class would need to define the following methods:

- [x] `createCodeField(opts)`: this would return a DOM element with two children, an insert button && an input field (similar to those in the ColorWidget). this would take an options object with the initial value to include in the input field && a callback function to fire if the user were to edit/change the input field's value. idea would also be that insert button it creates has the same behavior as those in the ColorWidget && AFrameComponentWidget (ie. injects the code into the editor when clicked)

- [x] `createSlider(opts)`: this would return a DOM element with children (including an input range) similar to the sliders created the ColorWidget && AFrameComponentWidget. i'm imagining all the props in the options object are optional (ie. they should have resonable defaults), but allow u to specify: **background** this could be a hex color, array of hex colors (if u want to generate a gradent background for the slider) or image path. **min**, **max** && **step** values for the input range/slider, **bubble** which takes a color if u want to create an option "bubble" which appears above the slider (like those found in the ColorWidget sliders) **label** which is a string to include to the left of the slider (like the "H" "S" "L" labels in the ColorWidget) && **change** a callback function to fire when the user moves the slider.

- [x] `parseCSS(string)`: i'm thinking this method would take a string of CSS code && parse out the property from it's value[s], here's some examples of what i'm imaging:
  - `parseCSS('font-size: 24px;')` would return 
  ```js
  { property: 'font-size', value: ['24px'] }
  ```
  - `parseCSS('padding: 5px 10px 5px 20px;')` would return 
  ```js
  { property: 'padding', value: ['5px', '10px', '5px', '20px'] }
  ```
  - `parseCSS('transform: translate(10px, 20px) rotate(90deg)')` would return 
  ```js
  { 
    property: 'transform', 
    value: [
      ['translate', '10px', '20px'],
      ['rotate', '90deg']
    ]
  }
  ```

as we keep developing code generator widgets i imagine there will be functionality that might make sense to continue to add in here, but these seem like the obvious first ones to me

**Comment by il41** [comment]
would label: 'PX' need a comma after it before the change option?

**Comment by nbriz** [comment]
@il41 woops, good catch (^_^) fixed it

**Comment by nbriz** [comment]
@il41 as per our convo, here's my "custom elements" crash course...

creating a [custom element](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) is as simple as...
```js
class CodeField extends HTMLElement {
  connectedCallback () {
    this.innerHTML = `<div>
        <button>insert</button>
        <input type="text">
    </div>`
  }
}

window.customElements.define('code-field', CodeField)
```

we extend the base HTMLElement class (this is the class all html elements are instances of) && we use the special Custom Element's API method `connectedCallback` which fires as soon as a new 'code fied' is added to the DOM. in programming we call this a "life cycle hook", a method that fires at a particular moment in a class's "life cycle".

b/c `this` is an HTML element, we can use `.innerHTML` or `appendChild()` or whatever other HTMLElement methods/props we want in there. then all u have to do to make it an "official HTML element" on ur page is call the `customElements.define('tag-name', ClassName)` (NOTE: custom element tags must have a `-` in the name)

[check it out](https://jsfiddle.net/5rjykupf/)

we could then do stuff like:
```html
<code-field></code-field>
```
or:
```js
const cf = document.createElement('code-field')
document.body.appendChild(cf)
```

i would just add this new class to the same `GenWidget.js` file, but make sure it's above the `GenWidget` class (b/c it needs to exist before u try to use it inside the class)

of course, this much we could have done w/out having to define a custom element. BUT where this becomes useful to solve the problem u're having is in how we can create custom attributes && properties for our custom element.

one thing to note: an HTMLElement's "property" is not the same as it's "attribute", as u know, we get an attribute by doing `ele.getAttribute('src')` && set it by doing `ele.setAttribute('src', 'cat.jpg')`. we get a property by calling `ele.src` && set it by reassigning it `ele.src = 'cat.jpg'` ...the fact that image elements have both a 'src' attribute && a 'src' property sorta abstracts this, but consider how the `className` property is named differently from the `class` attribute. i mention this b/c for our custom element's 'value' we're going to have to create both an attribute called "value" && a property called "value"

## Properites

So, here's how we create a property: b/c custom elements are simply classes that extend from HTMLElement we can use all the normal Object Oriented Programming (OOP) functionality of javascript classes. we could of course create properties this way:

```js
class CodeField extends HTMLElement {
  constructor () {
    super()
    this.value = 'initial value'
  }

  connectedCallback () {
    this.innerHTML = `<div>
        <button>insert</button>
        <input type="text">
    </div>`
  }
}

window.customElements.define('code-field', CodeField)
```

problem is, we want to use our custom element to "listen" for changes on that property, && by creating it via `this` there's no way to know if/when the user has changed the property's value, the way we accomplish this in OOP is by creating "getters" && "setters", the way we do that in JS classes is like this:

```js
class CodeField extends HTMLElement {
  constructor () {
    super()
    this._value = 'initial value'
  }

  get value () {
    return this._value
  }

  set value (val) {
    this._value = val
  }

  connectedCallback () {
    this.innerHTML = `<div>
        <button>insert</button>
        <input type="text">
    </div>`
  }
}

window.customElements.define('code-field', CodeField)
```

so in this example we have 2 properties a "private" property of `_value` (which the user isn't supposed to know about) && a public property of `value` which the user can use. so if the user calls `this.value` it runs the getter, which just returns whatever the value of `this._value` is. && if we want to change it the user can do `this.value = 'something new'` which essentially reassigns `this._value` to `'something new'`... so u might be thinking, if `.value` is just an alias for `._value` what's the point? ...the point is we can put other logic in the "getter" funcion, meaning anytime the user calls `this.value = 'something else'` we can do other stuff in that function as well (like change the value of `this.querySelector('input').value` for example)

## Attributes

now... in our case, `.value` isn't going to be an alias for some other "private" property, instead it's going to be an alias for our attribute... which raises the question, how do we add attributes to our custom element? i thiiiink (but i'm not 100% sure) all we really need to do is set an attribute `this.setAttribute('poop', '100')` && then it automatically exists (if we call `this.getAttribute('poop')` i'm 99.99% sure it'll return `'100'`)

...but that doesn't really do us any good. the whole reason we're using custom elements is b/c we want to listen for changes on an attribute (like we're doing via our property's setter), so how can we listen for `setAttribute` calls? this is where more Custom Elements API stuff comes in. similar to the `connectedCallback` method, there's another "life cycle hook" we get w/this API called `attributeChangedCallback` which fires every time our element's attribute changes it looks like this:
```js
class CodeField extends HTMLElement {
  connectedCallback () {
    this.innerHTML = `<div>
        <button>insert</button>
        <input type="text">
    </div>`
  }

  attributeChangedCallback (attrName, oldVal, newVal) {
    console.log(attrName, oldVal, newVal)
  }
}

window.customElements.define('code-field', CodeField)
```

the idea is everytime `setAttribute` is called, that method fires && gives u access to the name of the attribute that changed, the old value it had && whatever new value it got set to. but this wont' work "as is", there's another piece of the API we need to use, the `observedAttributes` property, in order to specify which of the attributes we want to listen for changes on, in our case we just want to listen for `this.setAttribute('value', '100')` changes, so we'd do this:

```js
class CodeField extends HTMLElement {
  connectedCallback () {
    this.innerHTML = `<div>
        <button>insert</button>
        <input type="text">
    </div>`
  }

  static get observedAttributes () {
    return ['value']
  }

  attributeChangedCallback (attrName, oldVal, newVal) {
    console.log(attrName, oldVal, newVal)
  }
}

window.customElements.define('code-field', CodeField)
```

now everytime we call `this.setAttribute('value', 'something')` our console log in the `attributeChangedCallback` will fire.


## putting it all together

ok, so now we need to sync our value property w/our value attribute, such that everytime our attribute changes our prop does too && vice-versa:

```js
class CodeField extends HTMLElement {
  connectedCallback () {
    this.innerHTML = `<div>
        <button>insert</button>
        <input type="text">
    </div>`
  }

  get value () {
    return this.getAttribute('value')
  }

  set value (val) {
    this.setAttribute('value', val)
  }

  static get observedAttributes () {
    return ['value']
  }

  attributeChangedCallback (attrName, oldVal, newVal) {
    if (newVal !== oldVal) this[attrName] = newVal
  }
}

window.customElements.define('code-field', CodeField)
```

NOTE: rather than saying `this.value = newVal` i'm doing `this[attrName] = newVal`, my thinking being if later we decide to add another attribute to our `observedAttributes` we don't need to add another line inside the life cycle hook. additionally, notice that i put that after a conditional checking to make sure that the newVal isn't equal to the oldVal, that's b/c i want to avoid a feedback loop.

think about it, if the usre were to reassign `this.value = '100'`, that calls the value "setter", which is calling `setAttribute`, which would trigger our `attributeChangedCallback` which will reset `this['value'] = '100'` && thus create a feedback loop which crashes the browser. ...so this way we only change the prop in the callbck IF it's different from whatever it currently is.


...so that's the general idea, u should be able to use those methods now to lisen for changes on both the prop && attribute && make changes to any of it's children (ie. the input) accordingly.
