### ISSUE TITLE
New SVGs for netnet's face

### ISSUE THREAD

**Issue by nbriz** [netizenorg/netnet.studio#78]
here's the current roster
```
  (◕ ◞ ◕)
  (- ◞ -)
  (◕ ✖ ◕)
  (✖ ︵ ✖)
  (◉ ⌄ ☉)

  (☉ ﹏ ☉)
  (◑ ﹏ ◑)
  (Ó ﹏ Ò)
  (ŏ ー ŏ)
  (ŏ ︵ ŏ)
  (ŏ . ŏ)
  (^ ⌄ ^)
  (^ ‿ ^)
  (^ ﹏ ^)
  (o ‿ o)
  (◠ ◡ ◠)
  (◠ ‿ ◠)
  (ᴖ ◞ ᴖ)
  (ᴖ ᴗ ᴖ)
  (◠ ᗜ ◠)
  (⇀ ‸ ↼)
  (⌣̀ _ ⌣́)

```

**Comment by sarahrooney** [comment]
[faces.zip](https://github.com/netizenorg/netnet.studio/files/5732668/faces.zip)
faaaaaaaces!

**Comment by nbriz** [comment]
@sarahrooney  rad!!! i'mma take a look at these now!
i just pushed the new `dev` branch, do u want to pull that down on ur end && create a new folder in the `www/images/` called "faces" && put these in there? also, did u try naming the files after the actual Unicode Character?

**Comment by nbriz** [comment]
@sarahrooney i updated the face system to use the new SVG :D 

https://user-images.githubusercontent.com/2506806/103043585-02fa1000-4543-11eb-947b-90de48992a8c.mp4

here's how it works, there's an `updateFace()` method in the `www/js/Menu.js` file, which (in the refactored version) gets instantiated as `NNW.menu` (`NNW`being the instancef of `www/js/NetNet.js`), which means u can test this method in the console by calling it like `NNW.menu.updateFace()`, it takes an optional object argument which can contain any of the following keys:
```js
NNW.menu.updateFace({
  leftEye: '◕',
  mouth: '◞',
  rightEye: '◕',
  lookAtCursor: true,
  animation: 'blink'
})
```
passing the unicode chars as strings works b/c the svg's are named that way, YAY! (side note: i've got an exception for "mouth-dot.svg" so that u can write `mouth: '.'` && it'll work)

but, we've got some issues, the SVG's viewBoxes are 200 x 200 (which is good, we want them all to be consistent && that size works nicely) but it seems some of the shapes extend beyond the parameters of the viewBox, here's a couple examples:
![Screenshot from 2020-12-23 17-26-24](https://user-images.githubusercontent.com/2506806/103043868-16f24180-4544-11eb-849e-ce6895710ca2.png)
![Screenshot from 2020-12-23 17-26-59](https://user-images.githubusercontent.com/2506806/103043870-19549b80-4544-11eb-89f6-5b4753a64610.png)
which means if u try to make a face like this:
```js
NNW.menu.updateFace({
  leftEye: 'Ó',
  mouth: '﹏',
  rightEye: 'Ò',
  lookAtCursor: false,
  animation: 'none'
})
```
u get this:
![Screenshot from 2020-12-23 17-27-57](https://user-images.githubusercontent.com/2506806/103043923-38ebc400-4544-11eb-98f9-56700bc00c79.png)

**Comment by nbriz** [comment]
@sarahrooney also, the way the system works is that i load the content of the svg file into an internal object, but not the svg image itself (this lets me edit details like the size && color to ensure that netnet's face always matches the current layout+theme).

i thought it would be cool if everytime netnet's face updates, the page's favicon updates to match the current eye. i tested this && it works, buuuuut unlike w/the face, the favicon has to be the actual svg file, meaning i can't change the color of the eye, so the favicon ends up reflecting the svg files default color `#000000` (which is hard to see, at least in my darkmode UI) so what would u think about making the default colors for all these SVGs `#c76ebc` for the sake of the favicon :)

**Comment by sarahrooney** [comment]
re: first comment -- this sounds great & makes total sense, i'll go through the svgs and make sure they're restricted to the 200x200 px viewbox! & re: 2nd comment -- i can totally do that. to clarify, you have to load the svg as an inline image for the favicon, so you dont have access to altering its fill or anything, right? that makes sense to me as i type it out lol. 
i'll push up to this branch when those changes are ready!

**Comment by nbriz** [comment]
> to clarify, you have to load the svg as an inline image for the favicon, so you dont have access to altering its fill or anything, right?

right! essentially changing the `href` value of `<link rel="icon" type="image/svg+xml" href="THIS.svg">` so SVG is rendered as is (can't change any of it's interior code)
>  i'll push up to the 78-svg branch when those changes are ready!

yay!

**Comment by nbriz** [comment]
@sarahrooney did we already fix this? should i close this issue?

**Comment by sarahrooney** [comment]
@nbriz i think it must be -- sorry i totally lost track of this ticket
let's close and if making new faces is still an issue we can open a new bug later!

**Comment by nbriz** [comment]
sounds good!
