### ISSUE TITLE
upon login, netnet resets

### ISSUE THREAD

**Issue by jonsatrom** [netizenorg/netnet.studio#88]
If user isn't logged in, makes something, trys to save, is prompted to do github auth, then returns to netnet, it's like a new session... work is lost...

**Comment by nbriz** [comment]
@jonsatrom ...yea, this is why netnet says: 

> "Ok, I'm going to send you over to GitHub, then they'll send you back over here. This means you will loose any unsaved data you currently have open, is that cool?"

...before it sends u over to get authenticated. but i'll think on how to make that process a little smoother. in the beta-v1 i had netnet remember (not just ur code, but ur place in a tutorial && other state data) so everything would get reloaded on page load to make it appear as though u never left (netnet would even say "welcome back")... but the code i wrote to accomplish that was real messy. one of the things that changed in the refactor was the way state mangment works. && as i started working on rewriting that particular piece of logic it felt like it was creating a domino effect of narly/necessary edits... && so i pulled back + opted for that message instead. ...but what do u think?

**Comment by jonsatrom** [comment]
Classically, I didn’t read the warning… so maybe emphasizing that at very least. 
What about doing the auth stuff in a target blank and then some sort of check when the function menu is clicked?

**Comment by nbriz** [comment]
target blank wouldn't solve the issue, it would just create two netnet tabs (one that's logged, && one that's logged in to a fresh pag). the way the auth works is that netnet sends u to GitHub, && the GitHub sends u (redirects) to netnet (w/the auth-creds in the request)

**Comment by jonsatrom** [comment]
Also thinking that we need a possible confirm on logout... Are you sure?
